# Generated by Django 4.1.1 on 2022-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'trocar válcula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento'), ('GEO', 'Geometria'), ('TDF', 'Troca de disco de freio'), ('TV', 'Troca de vela'), ('TF', 'Troca do farol frontal'), ('TS', 'Troca do farol traseiro')], max_length=3),
        ),
    ]
