# Generated by Django 4.1.1 on 2022-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_carro_ano_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
